### ISSUE TITLE
Fix Actions quality

### ISSUE THREAD

**Issue by kaitj** [khanlab/dbsc#37]
## The problem

Flake8 exceptions don't actually work the way they are set up and are not being ignored. Need to fix this so that the `quality` action passes

## Environment

* Operating System
* DBSC version

**Comment by tkkuehn** [comment]
See https://github.com/khanlab/labelmerge/pull/31 for a PR fixing basically the same issue.

**Comment by kaitj** [comment]
Fixed in #38
